name: Deploy to GitHub Pages
run-name: ${{ github.actor }} triggered the CI workflow 🚀

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v1

    - name: Set up Git
      run: |
        git config --global user.email "d.a.roor@uva.nl"
        git config --global user.name "D.A. Roor"

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Upload pages artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        name: github-pages
        path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment